[package]
name = "server"
version = "0.0.0"
edition = "2018"

[dependencies]
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.59"
serde_qs = "0.8"
simplelog = "0.10.0"
tiny_http = "0.6"
url = "2.2"
