name: server
description: A companion app for my server.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  black_hole_flutter: ^0.3.2
  dartx: ^0.7.1
  flutter:
    sdk: flutter
  http: ^0.13.3
  toml: ^0.11.0
  tuple: ^2.0.0
  syncfusion_flutter_charts: ^19.2.49

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ../Config.toml
